hosts:
  - name: server-lond-64
    environment: lab
    role: docker-host
    address: 192.168.120.64
    os: ubuntu-server-lts
    platform_root: /opt/docker
    portainer_environment: server-lab-01
    backup_profile: platform-standard
    status: active
